# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_dsp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignfilter',
            name='value',
            field=models.TextField(),
        ),
    ]
