# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_dsp'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='subscriber_selection_size',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
