# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-15 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dsp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safe_uid', models.CharField(blank=True, max_length=256, null=True)),
                ('active', models.BooleanField()),
                ('dsp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route_traffic.Dsp')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route_traffic.Node')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='router',
            unique_together=set([('node', 'dsp')]),
        ),
    ]
