# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-15 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route_traffic', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='router',
            unique_together=set([('node', 'dsp', 'safe_uid')]),
        ),
    ]
